apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    azure.workload.identity/client-id: azurerm_user_assigned_identity.argocd_identity.client_id
  labels:
    azure.workload.identity/use: "true"



# kubectl apply -f argocd-sa.yaml