apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app

resources:
- ../../base

labels:
- pairs:
    environment: dev


replicas:
- count: 1
  name: backend
- count: 1
  name: frontend


images:
- name: backend
  newName: 3tieracr.azurecr.io/3tier-azure/backend
  newTag: sha-ab875a7
- name: frontend
  newName: 3tieracr.azurecr.io/3tier-azure/frontend
  newTag: sha-ab875a7


patches:
- patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
  target:
    kind: HorizontalPodAutoscaler
    name: backend-hpa
